# Generated by Django 5.1.3 on 2024-12-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=220)),
                ('message', models.TextField()),
            ],
        ),
    ]
