# Generated by Django 5.1.3 on 2024-12-21 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0004_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('property_id', models.CharField(max_length=5)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.agent')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property_type')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.status')),
            ],
        ),
    ]
