# Generated by Django 5.1.3 on 2024-12-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Commentt',
        ),
    ]
